idf_component_register(
    SRCS
        "event_bus.c"
        "config_svc.c"
        "display_svc.c"
        "network_svc.c"
        "ota_svc.c"
        "notify_svc.c"
        "log_svc.c"
        "trace_svc.c"
        "mqtt_svc.c"
        "scheduler_svc.c"
        "hwtest_svc.c"
        "factory_svc.c"
        "auto_volt.c"
        "restart_svc.c"
    INCLUDE_DIRS
        "include"
    EMBED_TXTFILES
        "web/index.html"
        "web/devices.html"
        "web/manifest.json"
        "web/sw.js"
        "web/icon.svg"
        "web/hw.html"
        "web/hw_board_base.svg"
    REQUIRES
        tes_protocol
        tes_sm
        platform
        charger_hal
        drivers
        nvs_flash
        esp_wifi
        esp_http_server
        esp_https_ota
        app_update
        esp_http_client
        mbedtls
        json
        espressif__mdns
        mqtt
        esp_netif
        freertos
        esp_timer
        esp_driver_tsens
        esp_partition
)
